# Análise descritiva para confecção da tabela 1.

In [122]:
import pandas as pd
import numpy as np

caminho = r'C:\Users\saulosgil\OneDrive\Documentos\health_outcomes_workers\data\df_analise.csv'
df = pd.read_csv(caminho)

df.head()

,idade,sexo,estado_civil,escolaridade,renda_mensal,cor_raca,tempo_trab_anos,funcao_trab,carga_horaria_horas_sem,outro_trab,...,Diuretics,Beta_blockers,ACE_inhibitors,Metformin,CCB,whoqol_fisico,whoqol_psicologico,whoqol_social,whoqol_ambiente,whoqol_n_validos
0,34,feminino,separado,médio completo,1 a 3 salários mínimos,preto (a),1.0,cooperado,40,sim,...,0,0,0,0,0,71.43,70.83,83.33,78.12,26
1,59,masculino,divorciado,médio completo,mais de 3 salários,pardo (a),2.0,cooperado,56,não,...,0,0,0,0,0,100.00,83.33,100.00,93.75,26
2,27,masculino,solteiro,superior completo,mais de 3 salários,pardo (a),1.0,cooperado,44,não,...,0,0,0,0,0,78.57,58.33,75.00,75.00,26
3,40,masculino,solteiro,médio completo,1 a 3 salários mínimos,preto (a),1.0,cooperado,45,não,...,0,0,0,0,0,78.57,95.83,100.00,78.12,26
4,23,masculino,solteiro,médio completo,mais de 3 salários,preto (a),2.0,cooperado,45,não,...,0,0,0,0,0,75.00,83.33,66.67,90.62,26

## Calcular N (%) de cada valor da variável sexo

In [123]:
tabela = pd.DataFrame({
    'N': df['sexo'].value_counts().sort_index(),
    '%': df['sexo'].value_counts(normalize=True).sort_index().mul(100).round(0),
})
tabela

            N     %
sexo
feminino   23  52.0
masculino  21  48.0

## Criar variável `idade_cat` e calcular N (%) de cada valor

 - idade < 65;
 
 - idade >= 65.

In [124]:
idade = df['idade'].astype(int)

# Binária: < 65 = 1, >= 65 = 0, ausente = NaN
df['idade_cat'] = np.where(idade < 65, '< 65 anos', '>= 65 anos')

tabela = pd.DataFrame({
    'N': df['idade_cat'].value_counts().sort_index(),
    '%': df['idade_cat'].value_counts(normalize=True).sort_index().mul(100).round(0),
})
tabela

             N     %
idade_cat
< 65 anos   37  84.0
>= 65 anos   7  16.0

## Calcular N (%) de cada valor da variável `cor_raca`

In [125]:
tabela = pd.DataFrame({
    'N': df['cor_raca'].value_counts().sort_index(),
    '%': df['cor_raca'].value_counts(normalize=True).sort_index().mul(100).round(0),
})
tabela

              N     %
cor_raca
amarelo (a)   1   2.0
branco (a)   11  25.0
pardo (a)    21  48.0
preto (a)    11  25.0

## Calcular N (%) de cada valor da variável `estado_civil`

In [126]:
# juntar separado e divorciado
df['estado_civil'] = df['estado_civil'].replace({'divorciado': 'separado'})

tabela = pd.DataFrame({
    'N': df['estado_civil'].value_counts().sort_index(),
    '%': df['estado_civil'].value_counts(normalize=True).sort_index().mul(100).round(0),
})
tabela

               N     %
estado_civil
casado        15  34.0
separado       7  16.0
solteiro      21  48.0
viúvo          1   2.0

## Calcular N (%) de cada valor da variável `escolaridade`

In [127]:
mapa_escolaridade = {
    'não estudou':              'No formal education',
    'fundamental incompleto':   'Incomplete elementary school',
    'fundamental completo':     'Complete elementary school',
    'médio incompleto':         'Incomplete high school',
    'médio completo':           'High school graduate',
    'superior incompleto':      'Some college',
    'superior completo':        "College degree",
}

ordem = list(mapa_escolaridade.values())

df['escolaridade_en'] = pd.Categorical(
    df['escolaridade'].map(mapa_escolaridade),
    categories=ordem,
    ordered=True,
)

tabela = pd.DataFrame({
    'N': df['escolaridade_en'].value_counts().sort_index(),
    '%': df['escolaridade_en'].value_counts(normalize=True).sort_index().mul(100).round(0),
})
tabela

                               N     %
escolaridade_en
No formal education            1   2.0
Incomplete elementary school  15  34.0
Complete elementary school     6  14.0
Incomplete high school         5  11.0
High school graduate          12  27.0
Some college                   1   2.0
College degree                 4   9.0

## Calcular N (%) de cada valor da variável `renda_mensal`

In [128]:
tabela = pd.DataFrame({
    'N': df['renda_mensal'].value_counts().sort_index(),
    '%': df['renda_mensal'].value_counts(normalize=True).sort_index().mul(100).round(0),
})
tabela

                         N     %
renda_mensal
1 a 3 salários mínimos  35  80.0
faltou                   1   2.0
mais de 3 salários       7  16.0
sem renda                1   2.0

## Média de DP da variável `tempo_trab_anos`

In [129]:
print('Tempo de trabalho (em anos)')
print(f'Média:', df['tempo_trab_anos'].mean().round())
print(f'DP:', df['tempo_trab_anos'].std().round())

Tempo de trabalho (em anos)
Média: 3.0
DP: 2.0

## Média de DP da variável `carga_horaria_horas_sem`

In [130]:
print('Carga horária de horas trabalhadas por semana')
print(f'Média:', df['carga_horaria_horas_sem'].mean().round())
print(f'DP:', df['carga_horaria_horas_sem'].std().round())

Carga horária de horas trabalhadas por semana
Média: 45.0
DP: 13.0

## Calcular N (%) de cada valor da variável `tabacco`

In [131]:
tabela = pd.DataFrame({
    'N': df['tabacco'].value_counts().sort_index(),
    '%': df['tabacco'].value_counts(normalize=True).sort_index().mul(100).round(0),
})
tabela

             N     %
tabacco
Ex-fumante   1   2.0
Não         33  75.0
Sim         10  23.0

## Média de DP da variável `peso`

In [132]:
print('Peso corporal')
print(f'Média:', df['peso'].mean().round(1))
print(f'DP:', df['peso'].std().round(1))

Peso corporal
Média: 74.5
DP: 16.3

## Média de DP da variável `imc`

In [133]:
print('IMC')
print(f'Média:', df['imc'].mean().round(1))
print(f'DP:', df['imc'].std().round(1))

IMC
Média: 28.1
DP: 5.9

## Média de DP da variável `circun_abdome`

In [134]:
print('Waist circumference')
print(f'Média:', df['circun_abdome'].mean().round(1))
print(f'DP:', df['circun_abdome'].std().round(1))

Waist circumference
Média: 90.9
DP: 14.8

## Média de DP da variável `cintura_altura_ratio`

In [135]:
print('Waist-to-Height Ratio, a.u.')
print(f'Média:', df['cintura_altura_ratio'].mean().round(1))
print(f'DP:', df['cintura_altura_ratio'].std().round(1))

Waist-to-Height Ratio, a.u.
Média: 56.0
DP: 9.7

## Calcular N (%) de cada valor da variável `obesidade`

In [136]:
tabela = pd.DataFrame({
    'N': df['obesidade'].value_counts().sort_index(),
    '%': df['obesidade'].value_counts(normalize=True).sort_index().mul(100).round(0),
})
tabela

            N     %
obesidade
0          24  55.0
1          20  45.0

## Calcular N (%) de cada valor da variável `DM2`

In [137]:
tabela = pd.DataFrame({
    'N': df['DM2'].value_counts().sort_index(),
    '%': df['DM2'].value_counts(normalize=True).sort_index().mul(100).round(0),
})
tabela

      N     %
DM2
0    38  86.0
1     6  14.0

## Calcular N (%) de cada valor da variável `HAS`

In [138]:
tabela = pd.DataFrame({
    'N': df['HAS'].value_counts().sort_index(),
    '%': df['HAS'].value_counts(normalize=True).sort_index().mul(100).round(0),
})
tabela

      N      %
HAS
0    44  100.0

## Calcular N (%) de cada valor da variável `ARB`

In [139]:
tabela = pd.DataFrame({
    'N': df['ARB'].value_counts().sort_index(),
    '%': df['ARB'].value_counts(normalize=True).sort_index().mul(100).round(0),
})
tabela

      N     %
ARB
0    39  89.0
1     5  11.0

## Calcular N (%) de cada valor da variável `Diuretics`

In [140]:
tabela = pd.DataFrame({
    'N': df['Diuretics'].value_counts().sort_index(),
    '%': df['Diuretics'].value_counts(normalize=True).sort_index().mul(100).round(0),
})
tabela

            N     %
Diuretics
0          39  89.0
1           5  11.0

## Calcular N (%) de cada valor da variável `Beta_blockers`

In [141]:
tabela = pd.DataFrame({
    'N': df['Beta_blockers'].value_counts().sort_index(),
    '%': df['Beta_blockers'].value_counts(normalize=True).sort_index().mul(100).round(0),
})
tabela

                N     %
Beta_blockers
0              42  95.0
1               2   5.0

## Calcular N (%) de cada valor da variável `ACE_inhibitors`

In [142]:
tabela = pd.DataFrame({
    'N': df['ACE_inhibitors'].value_counts().sort_index(),
    '%': df['ACE_inhibitors'].value_counts(normalize=True).sort_index().mul(100).round(0),
})
tabela

                 N     %
ACE_inhibitors
0               43  98.0
1                1   2.0

## Calcular N (%) de cada valor da variável `Metformin`

In [143]:
tabela = pd.DataFrame({
    'N': df['Metformin'].value_counts().sort_index(),
    '%': df['Metformin'].value_counts(normalize=True).sort_index().mul(100).round(0),
})
tabela

            N      %
Metformin
0          44  100.0

## Calcular N (%) de cada valor da variável `CCB`

In [144]:
tabela = pd.DataFrame({
    'N': df['CCB'].value_counts().sort_index(),
    '%': df['CCB'].value_counts(normalize=True).sort_index().mul(100).round(0),
})
tabela

      N     %
CCB
0    43  98.0
1     1   2.0

## Tabela 1. PRONTA!!!
![Tabela 1. PRONTA!!!](https://tse4.mm.bing.net/th/id/OIP._v4UoQgLAF8azzInS_1P6AHaH4?r=0&rs=1&pid=ImgDetMain&o=7&rm=3)