# **Preparação dos dados**

Importação dos dados e verificação do shape, colunas, tipos de dados, quantidade de dados ausentes e duplicados.

In [70]:
# Bibliotecas
import pandas as pd
import numpy as np

In [71]:
caminho = r'C:\Users\saulosgil\OneDrive\Documentos\health_outcomes_workers\data\df.xlsx'
df = pd.read_excel(caminho)

# Quantas linhas e colunas existem?
print(f'O número de linhas e colunas do dataset é: {df.shape[0]} linhas e {df.shape[1]} colunas')
print(80 *'-')

print("Colunas da base:")
print(df.columns)
print(80 *'-')

print("Tipos de dados:")
print(df.dtypes)
print(80 *'-')

print("Quantidade de valores ausentes por coluna:")
print(df.isna().sum())
print(80 *'-')

print("\nNúmero de linhas duplicadas:", df.duplicated().sum())

O número de linhas e colunas do dataset é: 44 linhas e 66 colunas
--------------------------------------------------------------------------------
Colunas da base:
Index(['unidade', 'idade ', 'sexo', 'estado_civil', 'escolaridade',
       'renda_mensal', 'n_pessoas_domicilio', 'tipo_moradia', 'tempo_moradia',
       'cor_raca', 'tempo_trab_anos', 'funcao_trab', 'carga_horaria_horas_sem',
       'forma_remuneracao', 'outro_trab', 'ja_trab_outro_local_reciclagem',
       'utiliza_epi', 'quais_epis', 'recebe_treino_segurança',
       'ja_sofreu_acid_trab', 'percepcao_condicoes_trab',
       'exposicao_percebida', 'tabacco', 'bebida', 'freq_bebida',
       'diagnostico', 'acompanhamento_medico', 'medicamentos',
       'como_avalia_propria_saude', 'who1', 'who2', 'who3', 'who4', 'who5',
       'who6', 'who7', 'who8', 'who9', 'who10', 'who11', 'who12', 'who13',
       'who14', 'who15', 'who16', 'who17', 'who18', 'who19', 'who20', 'who21',
       'who22', 'who23', 'who24', 'who25', 'who26', 'peso', 'estatura', 'imc',
       'imc_classe', 'circun_abdome', 'circun_pant', 'pas', 'pad', 'hgs_dir',
       'hgs_esq', 'cintura_altura_ratio'],
      dtype='str')
--------------------------------------------------------------------------------
Tipos de dados:
unidade                     str
idade                     int64
sexo                        str
estado_civil                str
escolaridade                str
                         ...
pas                       int64
pad                       int64
hgs_dir                 float64
hgs_esq                 float64
cintura_altura_ratio    float64
Length: 66, dtype: object
--------------------------------------------------------------------------------
Quantidade de valores ausentes por coluna:
unidade                 0
idade                   0
sexo                    0
estado_civil            0
escolaridade            0
                       ..
pas                     0
pad                     0
hgs_dir                 0
hgs_esq                 0
cintura_altura_ratio    0
Length: 66, dtype: int64
--------------------------------------------------------------------------------

Número de linhas duplicadas: 0

In [72]:
df.head(5)

,unidade,idade,sexo,estado_civil,escolaridade,renda_mensal,n_pessoas_domicilio,tipo_moradia,tempo_moradia,cor_raca,...,estatura,imc,imc_classe,circun_abdome,circun_pant,pas,pad,hgs_dir,hgs_esq,cintura_altura_ratio
0,matriz,34,feminino,separado,médio completo,1 a 3 salários mínimos,6,própria,33 anos,preto (a),...,1.60,33.95,obesidade grau I,96.0,45.0,120,90,29.8,23.0,60.000000
1,matriz,59,masculino,divorciado,médio completo,mais de 3 salários,2,própria,6 anos,pardo (a),...,1.57,25.96,sobrepeso,82.0,39.0,110,70,22.9,31.2,52.229299
2,matriz,27,masculino,solteiro,superior completo,mais de 3 salários,4,alugada,10 anos,pardo (a),...,1.76,34.70,obesidade grau I,102.0,44.0,130,90,37.2,46.3,57.954545
3,matriz,40,masculino,solteiro,médio completo,1 a 3 salários mínimos,1,alugada,10 anos,preto (a),...,1.69,20.66,eutrófico,78.0,35.5,110,80,41.5,41.3,46.153846
4,matriz,23,masculino,solteiro,médio completo,mais de 3 salários,2,própria,1 ano,preto (a),...,1.83,21.74,eutrófico,86.5,38.0,120,70,40.7,42.7,47.267760

In [73]:
df.tail(5)

,unidade,idade,sexo,estado_civil,escolaridade,renda_mensal,n_pessoas_domicilio,tipo_moradia,tempo_moradia,cor_raca,...,estatura,imc,imc_classe,circun_abdome,circun_pant,pas,pad,hgs_dir,hgs_esq,cintura_altura_ratio
39,matriz,65,masculino,casado,fundamental incompleto,1 a 3 salários mínimos,5,cedida,25 anos,pardo (a),...,1.63,26.08,sobrepeso,86.0,36.0,120,80,44.4,36.5,52.760736
40,matriz,41,masculino,solteiro,fundamental incompleto,1 a 3 salários mínimos,4,cedida,27 anos,pardo (a),...,1.64,24.39,eutrófico,85.0,36.0,120,80,22.5,27.5,51.829268
41,matriz,47,masculino,casado,fundamental incompleto,sem renda,5,alugada,36 anos,amarelo (a),...,1.67,30.01,obesidade grau I,99.0,41.0,120,80,40.2,29.4,59.281437
42,matriz,29,feminino,casado,superior completo,mais de 3 salários,3,própria,29 anos,pardo (a),...,1.67,30.94,obesidade grau I,90.0,42.0,130,80,29.7,31.0,53.892216
43,matriz,18,masculino,solteiro,fundamental incompleto,1 a 3 salários mínimos,3,própria,17 anos,pardo (a),...,1.76,19.82,eutrófico,72.5,33.0,120,70,35.9,35.2,41.193182

In [74]:
# características do dataset com skimpy
import skimpy as skim

skim.skim(df)

╭──────────────────────────────────────────────── skimpy summary ─────────────────────────────────────────────────╮
│          Data Summary                Data Types                                                                 │
│ ┏━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┓ ┏━━━━━━━━━━━━━┳━━━━━━━┓                                                          │
│ ┃ Dataframe         ┃ Values ┃ ┃ Column Type ┃ Count ┃                                                          │
│ ┡━━━━━━━━━━━━━━━━━━━╇━━━━━━━━┩ ┡━━━━━━━━━━━━━╇━━━━━━━┩                                                          │
│ │ Number of rows    │ 44     │ │ int64       │ 31    │                                                          │
│ │ Number of columns │ 66     │ │ string      │ 26    │                                                          │
│ └───────────────────┴────────┘ │ float64     │ 9     │                                                          │
│                                └─────────────┴───────┘                                                          │
│                                                     number                                                      │
│ ┏━━━━━━━━━━━━━━━━━┳━━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━┳━━━━━━━━━┳━━━━━━━┳━━━━━━━┳━━━━━━━┳━━━━━━━┳━━━━━━━┳━━━━━━━━┓  │
│ ┃ column          ┃ NA ┃ NA %             ┃ mean  ┃ sd      ┃ p0    ┃ p25   ┃ p50   ┃ p75   ┃ p100  ┃ hist   ┃  │
│ ┡━━━━━━━━━━━━━━━━━╇━━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━╇━━━━━━━━━╇━━━━━━━╇━━━━━━━╇━━━━━━━╇━━━━━━━╇━━━━━━━╇━━━━━━━━┩  │
│ │      idade      │  0 │                0 │ 45.95 │   15.32 │    18 │ 32.75 │  45.5 │ 58.25 │    77 │ ▃▇▅▅▇▁ │  │
│ │ n_pessoas_domic │  0 │                0 │ 3.295 │    2.53 │     1 │     2 │     3 │  4.25 │    14 │  ▇▂▁   │  │
│ │      ilio       │    │                  │       │         │       │       │       │       │       │        │  │
│ │ tempo_trab_anos │ 16 │ 36.3636363636363 │ 2.679 │   1.964 │     1 │     1 │     2 │  3.25 │     8 │ ▇▂▁▁ ▁ │  │
│ │                 │    │                7 │       │         │       │       │       │       │       │        │  │
│ │ carga_horaria_h │  0 │                0 │ 45.05 │   12.56 │    18 │ 38.75 │    42 │    56 │    74 │ ▁▃▇▁▃▁ │  │
│ │    oras_sem     │    │                  │       │         │       │       │       │       │       │        │  │
│ │      who1       │  0 │                0 │ 3.977 │   1.023 │     1 │     3 │     4 │     5 │     5 │    ▆▅▇ │  │
│ │      who2       │  0 │                0 │ 3.909 │    1.03 │     1 │     3 │     4 │     5 │     5 │ ▁▁ ▇▆▇ │  │
│ │      who3       │  0 │                0 │ 2.636 │    1.74 │     1 │     1 │   2.5 │     5 │     5 │ ▇  ▃▁▅ │  │
│ │      who4       │  0 │                0 │ 2.977 │   1.811 │     1 │     1 │     3 │     5 │     5 │ ▇  ▂▂▇ │  │
│ │      who5       │  0 │                0 │ 3.818 │   1.281 │     1 │     3 │     4 │     5 │     5 │ ▁▂ ▅▃▇ │  │
│ │      who6       │  0 │                0 │ 4.773 │  0.4756 │     3 │     5 │     5 │     5 │     5 │    ▂ ▇ │  │
│ │      who7       │  0 │                0 │ 4.182 │   1.063 │     2 │     3 │     5 │     5 │     5 │ ▁ ▃ ▂▇ │  │
│ │      who8       │  0 │                0 │ 4.523 │  0.8209 │     3 │     4 │     5 │     5 │     5 │ ▂  ▁ ▇ │  │
│ │      who9       │  0 │                0 │  4.25 │  0.9675 │     2 │     3 │     5 │     5 │     5 │ ▁ ▃ ▂▇ │  │
│ │      who10      │  0 │                0 │ 4.432 │  0.8733 │     2 │     4 │     5 │     5 │     5 │   ▂ ▂▇ │  │
│ │      who11      │  0 │                0 │ 4.568 │  0.8463 │     2 │  4.75 │     5 │     5 │     5 │   ▁ ▁▇ │  │
│ │      who12      │  0 │                0 │ 3.727 │   1.301 │     1 │     3 │     4 │     5 │     5 │ ▂▁ ▆▃▇ │  │
│ │      who13      │  0 │                0 │ 4.591 │  0.9721 │     1 │     5 │     5 │     5 │     5 │    ▁▁▇ │  │
│ │      who14      │  0 │                0 │ 3.909 │   1.235 │     1 │     3 │     4 │     5 │     5 │ ▁▁ ▅▃▇ │  │
│ │      who15      │  0 │                0 │ 4.682 │  0.9344 │     1 │     5 │     5 │     5 │     5 │      ▇ │  │
│ │      who16      │  0 │                0 │ 4.045 │   1.311 │     1 │     3 │     5 │     5 │     5 │ ▁▁ ▃▁▇ │  │
│ │      who17      │  0 │                0 │ 4.409 │   1.041 │     1 │     4 │     5 │     5 │     5 │  ▁ ▂▁▇ │  │
│ │      who18      │  0 │                0 │ 4.591 │  0.8975 │     1 │     5 │     5 │     5 │     5 │    ▁▁▇ │  │
│ │      who19      │  0 │                0 │ 4.364 │   1.036 │     1 │     4 │     5 │     5 │     5 │  ▁ ▂▂▇ │  │
│ │      who20      │  0 │                0 │ 4.068 │   1.319 │     1 │  3.75 │     5 │     5 │     5 │ ▁▂ ▁▃▇ │  │
│ │      who21      │  0 │                0 │ 3.705 │   1.488 │     1 │     3 │     4 │     5 │     5 │ ▂▂ ▃▂▇ │  │
│ │      who22      │  0 │                0 │ 3.909 │    1.46 │     1 │     3 │     5 │     5 │     5 │ ▂▁ ▂▂▇ │  │
│ │      who23      │  0 │                0 │ 4.409 │  0.8712 │     2 │     4 │     5 │     5 │     5 │   ▂ ▂▇ │  │
│ │      who24      │  0 │                0 │  4.25 │   1.241 │     1 │     4 │     5 │     5 │     5 │ ▁▁ ▁▁▇ │  │
│ │      who25      │  0 │                0 │ 4.318 │   1.216 │     1 │     4 │     5 │     5 │     5 │ ▁  ▂▁▇ │  │
│ │      who26      │  0 │                0 │ 2.841 │   1.539 │     1 │     1 │     3 │     4 │     5 │ ▇▂ ▆▃▅ │  │
│ │      peso       │  0 │                0 │ 74.45 │   16.32 │  43.1 │ 64.38 │ 73.35 │ 83.48 │ 111.1 │ ▃▆▇▇▁▂ │  │
│ │    estatura     │  0 │                0 │ 1.628 │ 0.09428 │  1.45 │ 1.558 │  1.62 │  1.69 │  1.86 │ ▁▇▆▃▃▁ │  │
│ │       imc       │  0 │                0 │ 28.13 │   5.855 │ 17.71 │ 22.73 │ 27.98 │ 33.05 │ 39.45 │ ▆▆▇▇▇▃ │  │
│ │  circun_abdome  │  0 │                0 │ 90.91 │   14.82 │    56 │ 82.75 │    91 │    99 │   122 │ ▁▂▅▇▂▂ │  │
│ │   circun_pant   │  0 │                0 │ 36.55 │    3.94 │    28 │    34 │    36 │ 38.25 │    46 │ ▁▅▇▇▂▂ │  │
│ │       pas       │  0 │                0 │ 123.5 │   14.61 │   100 │ 117.5 │   120 │   130 │   180 │  ▅▇▅▂  │  │
│ │       pad       │  0 │                0 │ 73.18 │   18.52 │     0 │    70 │    80 │    80 │    90 │ ▁   ▆▇ │  │
│ │     hgs_dir     │  0 │                0 │ 31.83 │   10.18 │  14.7 │  23.9 │  29.9 │  38.7 │  61.8 │ ▅▇▆▅▁▁ │  │
│ │     hgs_esq     │  0 │                0 │ 29.57 │   8.644 │  14.2 │ 23.23 │  29.3 │ 35.38 │  55.7 │ ▅▇▇▆▁▁ │  │
│ │ cintura_altura_ │  0 │                0 │ 56.03 │     9.7 │ 32.94 │ 49.55 │ 54.97 │ 62.72 │    75 │ ▁▅▇▇▅▃ │  │
│ │      ratio      │    │                  │       │         │       │       │       │       │       │        │  │
│ └─────────────────┴────┴──────────────────┴───────┴─────────┴───────┴───────┴───────┴───────┴───────┴────────┘  │
│                                                     string                                                      │
│ ┏━━━━━━━━━━━┳━━━━┳━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━┓  │
│ ┃           ┃    ┃           ┃          ┃           ┃          ┃           ┃ chars    ┃ words per ┃ total    ┃  │
│ ┃ column    ┃ NA ┃ NA %      ┃ shortest ┃ longest   ┃ min      ┃ max       ┃ per row  ┃ row       ┃ words    ┃  │
│ ┡━━━━━━━━━━━╇━━━━╇━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━┩  │
│ │  unidade  │  0 │         0 │  matriz  │ carolina  │ carolina │  matriz   │     10.5 │       1.8 │       80 │  │
│ │           │    │           │          │ de jesus  │ de jesus │           │          │           │          │  │
│ │   sexo    │  0 │         0 │ feminino │ masculino │ feminino │ masculino │     8.48 │         1 │       44 │  │
│ │ estado_ci │  0 │         0 │  viúvo   │ divorciad │  casado  │   viúvo   │      7.3 │         1 │       44 │  │
│ │    vil    │    │           │          │     o     │          │           │          │           │          │  │
│ │ escolarid │  0 │         0 │   não    │ fundament │ fundamen │ superior  │     18.1 │         2 │       88 │  │
│ │    ade    │    │           │ estudou  │    al     │   tal    │ incomplet │          │           │          │  │
│ │           │    │           │          │ incomplet │ completo │     o     │          │           │          │  │
│ │           │    │           │          │     o     │          │           │          │           │          │  │
│ │ renda_men │  0 │         0 │  faltou  │   1 a 3   │  1 a 3   │ sem renda │     20.7 │       4.7 │      206 │  │
│ │    sal    │    │           │          │ salários  │ salários │           │          │           │          │  │
│ │           │    │           │          │  mínimos  │ mínimos  │           │          │           │          │  │
│ │ tipo_mora │  0 │         0 │  cedida  │  própria  │ alugada  │  própria  │     6.93 │         1 │       44 │  │
│ │    dia    │    │           │          │           │          │           │          │           │          │  │
│ │ tempo_mor │  0 │         0 │  1 ano   │ não sabe  │  1 ano   │ não sabe  │     6.77 │         2 │       88 │  │
│ │   adia    │    │           │          │           │          │           │          │           │          │  │
│ │ cor_raca  │  0 │         0 │  preto   │  amarelo  │ amarelo  │ preto (a) │      9.3 │         2 │       88 │  │
│ │           │    │           │   (a)    │    (a)    │   (a)    │           │          │           │          │  │
│ │ funcao_tr │  0 │         0 │ cooperad │ individua │ cooperad │ individua │     9.39 │         1 │       44 │  │
│ │    ab     │    │           │    o     │     l     │    o     │     l     │          │           │          │  │
│ │ forma_rem │  0 │         0 │   fixa   │    por    │   fixa   │    por    │     11.6 │         2 │       86 │  │
│ │ uneracao  │    │           │          │ produção  │          │ produção  │          │           │          │  │
│ │ outro_tra │  0 │         0 │   sim    │    sim    │   não    │    sim    │        3 │         1 │       44 │  │
│ │     b     │    │           │          │           │          │           │          │           │          │  │
│ │ ja_trab_o │  0 │         0 │   não    │    não    │   não    │    sim    │        3 │         1 │       44 │  │
│ │ utro_loca │    │           │          │           │          │           │          │           │          │  │
│ │ l_recicla │    │           │          │           │          │           │          │           │          │  │
│ │    gem    │    │           │          │           │          │           │          │           │          │  │
│ │ utiliza_e │  0 │         0 │  nunca   │ as vezes  │ as vezes │  sempre   │     6.02 │         1 │       46 │  │
│ │    pi     │    │           │          │           │          │           │          │           │          │  │
│ │ quais_epi │  0 │         0 │   Bota   │   Luva,   │   Bota   │    não    │     32.8 │       4.7 │      208 │  │
│ │     s     │    │           │          │ máscara,  │          │  utiliza  │          │           │          │  │
│ │           │    │           │          │   bota,   │          │   (puxa   │          │           │          │  │
│ │           │    │           │          │ avental,  │          │  fardo,   │          │           │          │  │
│ │           │    │           │          │ protetor  │          │ não fica  │          │           │          │  │
│ │           │    │           │          │ auricular │          │    na     │          │           │          │  │
│ │           │    │           │          │     ,     │          │ esteira)  │          │           │          │  │
│ │           │    │           │          │ capacete, │          │           │          │           │          │  │
│ │           │    │           │          │  óculos   │          │           │          │           │          │  │
│ │ recebe_tr │  0 │         0 │   sim    │    sim    │   não    │    sim    │        3 │         1 │       44 │  │
│ │ eino_segu │    │           │          │           │          │           │          │           │          │  │
│ │   rança   │    │           │          │           │          │           │          │           │          │  │
│ │ ja_sofreu │  0 │         0 │   não    │    não    │   não    │    sim    │        3 │         1 │       44 │  │
│ │ _acid_tra │    │           │          │           │          │           │          │           │          │  │
│ │     b     │    │           │          │           │          │           │          │           │          │  │
│ │ percepcao │  0 │         0 │   boas   │ regulares │   boas   │   ruins   │     4.82 │         1 │       44 │  │
│ │ _condicoe │    │           │          │           │          │           │          │           │          │  │
│ │  s_trab   │    │           │          │           │          │           │          │           │          │  │
│ │ exposicao │  0 │         0 │   nega   │  poeira,  │  cheiro  │  ruídos   │     23.6 │         3 │      131 │  │
│ │ _percebid │    │           │          │  cheiro,  │          │           │          │           │          │  │
│ │     a     │    │           │          │ cortantes │          │           │          │           │          │  │
│ │           │    │           │          │     ,     │          │           │          │           │          │  │
│ │           │    │           │          │ químicos, │          │           │          │           │          │  │
│ │           │    │           │          │  ruídos   │          │           │          │           │          │  │
│ │  tabacco  │  0 │         0 │   Não    │ Ex-fumant │ Ex-fuman │    Sim    │     3.16 │         1 │       44 │  │
│ │           │    │           │          │     e     │    te    │           │          │           │          │  │
│ │  bebida   │  0 │         0 │   Não    │    Sim    │   Não    │    Sim    │     3.02 │         1 │       45 │  │
│ │ freq_bebi │ 20 │ 45.454545 │    ?     │  3x ou +  │ 1-2x sem │   raro    │     6.29 │         1 │       45 │  │
│ │    da     │    │  45454545 │          │    sem    │          │           │          │           │          │  │
│ │ diagnosti │  0 │         0 │    DM    │ CA, pedra │ Aneurism │ Trombose  │      6.7 │       1.5 │       65 │  │
│ │    co     │    │           │          │ vesícula, │    a     │     e     │          │           │          │  │
│ │           │    │           │          │ aderência │ Cerebral │ alopécia  │          │           │          │  │
│ │           │    │           │          │ intestina │    e     │           │          │           │          │  │
│ │           │    │           │          │     l     │ Osteopor │           │          │           │          │  │
│ │           │    │           │          │           │   ose    │           │          │           │          │  │
│ │ acompanha │  0 │         0 │   sim    │    sim    │   não    │    sim    │        3 │         1 │       44 │  │
│ │ mento_med │    │           │          │           │          │           │          │           │          │  │
│ │    ico    │    │           │          │           │          │           │          │           │          │  │
│ │ medicamen │  0 │         0 │   não    │ losartana │  alenia  │ sertralin │        9 │       1.5 │       68 │  │
│ │    tos    │    │           │          │     ,     │          │    a e    │          │           │          │  │
│ │           │    │           │          │ atenolol  │          │ quetiapin │          │           │          │  │
│ │           │    │           │          │     e     │          │     a     │          │           │          │  │
│ │           │    │           │          │ anlodipin │          │           │          │           │          │  │
│ │           │    │           │          │     o     │          │           │          │           │          │  │
│ │ como_aval │  1 │ 2.2727272 │   boa    │ muito boa │   boa    │  regular  │     5.84 │       1.2 │       52 │  │
│ │ ia_propri │    │  72727273 │          │           │          │           │          │           │          │  │
│ │  a_saude  │    │           │          │           │          │           │          │           │          │  │
│ │ imc_class │  0 │         0 │ sobrepes │ obesidade │ eutrófic │ sobrepeso │     12.5 │         2 │       88 │  │
│ │     e     │    │           │    o     │  grau II  │    o     │           │          │           │          │  │
│ └───────────┴────┴───────────┴──────────┴───────────┴──────────┴───────────┴──────────┴───────────┴──────────┘  │
╰────────────────────────────────────────────────────── End ──────────────────────────────────────────────────────╯

## Tratamento dos valores ausentes

In [75]:
# 1. Separar apenas as colunas numéricas
num_cols = df.select_dtypes(include='number').columns

# 2. Separar apenas as colunas de texto
str_cols = df.select_dtypes(include='str').columns

# 3. Preencher os NaN com a média de cada coluna (no próprio df)
df[num_cols] = df[num_cols].fillna(df[num_cols].mean())

# 4. Preencher os NaN com a moda de cada coluna (no próprio df)
df[str_cols] = df[str_cols].fillna(df[str_cols].mode().iloc[0])

print("Quantidade de valores ausentes por coluna depois da imputação:")
print(df.isna().sum())
print(80 *'-')

Quantidade de valores ausentes por coluna depois da imputação:
unidade                 0
idade                   0
sexo                    0
estado_civil            0
escolaridade            0
                       ..
pas                     0
pad                     0
hgs_dir                 0
hgs_esq                 0
cintura_altura_ratio    0
Length: 66, dtype: int64
--------------------------------------------------------------------------------

In [76]:
# características do dataset com skimpy após a imputação (não deve haver valores ausentes)
import skimpy as skim

skim.skim(df)

╭──────────────────────────────────────────────── skimpy summary ─────────────────────────────────────────────────╮
│          Data Summary                Data Types                                                                 │
│ ┏━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┓ ┏━━━━━━━━━━━━━┳━━━━━━━┓                                                          │
│ ┃ Dataframe         ┃ Values ┃ ┃ Column Type ┃ Count ┃                                                          │
│ ┡━━━━━━━━━━━━━━━━━━━╇━━━━━━━━┩ ┡━━━━━━━━━━━━━╇━━━━━━━┩                                                          │
│ │ Number of rows    │ 44     │ │ int64       │ 31    │                                                          │
│ │ Number of columns │ 66     │ │ string      │ 26    │                                                          │
│ └───────────────────┴────────┘ │ float64     │ 9     │                                                          │
│                                └─────────────┴───────┘                                                          │
│                                                     number                                                      │
│ ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━┳━━━━━━━┳━━━━━━━┳━━━━━━━━━┳━━━━━━━┳━━━━━━━┳━━━━━━━┳━━━━━━━┳━━━━━━━┳━━━━━━━━┓  │
│ ┃ column                    ┃ NA  ┃ NA %  ┃ mean  ┃ sd      ┃ p0    ┃ p25   ┃ p50   ┃ p75   ┃ p100  ┃ hist   ┃  │
│ ┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━╇━━━━━━━╇━━━━━━━╇━━━━━━━━━╇━━━━━━━╇━━━━━━━╇━━━━━━━╇━━━━━━━╇━━━━━━━╇━━━━━━━━┩  │
│ │           idade           │   0 │     0 │ 45.95 │   15.32 │    18 │ 32.75 │  45.5 │ 58.25 │    77 │ ▃▇▅▅▇▁ │  │
│ │    n_pessoas_domicilio    │   0 │     0 │ 3.295 │    2.53 │     1 │     2 │     3 │  4.25 │    14 │  ▇▂▁   │  │
│ │      tempo_trab_anos      │   0 │     0 │ 2.679 │   1.556 │     1 │     2 │ 2.679 │ 2.759 │     8 │ ▇▇▁▁ ▁ │  │
│ │  carga_horaria_horas_sem  │   0 │     0 │ 45.05 │   12.56 │    18 │ 38.75 │    42 │    56 │    74 │ ▁▃▇▁▃▁ │  │
│ │           who1            │   0 │     0 │ 3.977 │   1.023 │     1 │     3 │     4 │     5 │     5 │    ▆▅▇ │  │
│ │           who2            │   0 │     0 │ 3.909 │    1.03 │     1 │     3 │     4 │     5 │     5 │ ▁▁ ▇▆▇ │  │
│ │           who3            │   0 │     0 │ 2.636 │    1.74 │     1 │     1 │   2.5 │     5 │     5 │ ▇  ▃▁▅ │  │
│ │           who4            │   0 │     0 │ 2.977 │   1.811 │     1 │     1 │     3 │     5 │     5 │ ▇  ▂▂▇ │  │
│ │           who5            │   0 │     0 │ 3.818 │   1.281 │     1 │     3 │     4 │     5 │     5 │ ▁▂ ▅▃▇ │  │
│ │           who6            │   0 │     0 │ 4.773 │  0.4756 │     3 │     5 │     5 │     5 │     5 │    ▂ ▇ │  │
│ │           who7            │   0 │     0 │ 4.182 │   1.063 │     2 │     3 │     5 │     5 │     5 │ ▁ ▃ ▂▇ │  │
│ │           who8            │   0 │     0 │ 4.523 │  0.8209 │     3 │     4 │     5 │     5 │     5 │ ▂  ▁ ▇ │  │
│ │           who9            │   0 │     0 │  4.25 │  0.9675 │     2 │     3 │     5 │     5 │     5 │ ▁ ▃ ▂▇ │  │
│ │           who10           │   0 │     0 │ 4.432 │  0.8733 │     2 │     4 │     5 │     5 │     5 │   ▂ ▂▇ │  │
│ │           who11           │   0 │     0 │ 4.568 │  0.8463 │     2 │  4.75 │     5 │     5 │     5 │   ▁ ▁▇ │  │
│ │           who12           │   0 │     0 │ 3.727 │   1.301 │     1 │     3 │     4 │     5 │     5 │ ▂▁ ▆▃▇ │  │
│ │           who13           │   0 │     0 │ 4.591 │  0.9721 │     1 │     5 │     5 │     5 │     5 │    ▁▁▇ │  │
│ │           who14           │   0 │     0 │ 3.909 │   1.235 │     1 │     3 │     4 │     5 │     5 │ ▁▁ ▅▃▇ │  │
│ │           who15           │   0 │     0 │ 4.682 │  0.9344 │     1 │     5 │     5 │     5 │     5 │      ▇ │  │
│ │           who16           │   0 │     0 │ 4.045 │   1.311 │     1 │     3 │     5 │     5 │     5 │ ▁▁ ▃▁▇ │  │
│ │           who17           │   0 │     0 │ 4.409 │   1.041 │     1 │     4 │     5 │     5 │     5 │  ▁ ▂▁▇ │  │
│ │           who18           │   0 │     0 │ 4.591 │  0.8975 │     1 │     5 │     5 │     5 │     5 │    ▁▁▇ │  │
│ │           who19           │   0 │     0 │ 4.364 │   1.036 │     1 │     4 │     5 │     5 │     5 │  ▁ ▂▂▇ │  │
│ │           who20           │   0 │     0 │ 4.068 │   1.319 │     1 │  3.75 │     5 │     5 │     5 │ ▁▂ ▁▃▇ │  │
│ │           who21           │   0 │     0 │ 3.705 │   1.488 │     1 │     3 │     4 │     5 │     5 │ ▂▂ ▃▂▇ │  │
│ │           who22           │   0 │     0 │ 3.909 │    1.46 │     1 │     3 │     5 │     5 │     5 │ ▂▁ ▂▂▇ │  │
│ │           who23           │   0 │     0 │ 4.409 │  0.8712 │     2 │     4 │     5 │     5 │     5 │   ▂ ▂▇ │  │
│ │           who24           │   0 │     0 │  4.25 │   1.241 │     1 │     4 │     5 │     5 │     5 │ ▁▁ ▁▁▇ │  │
│ │           who25           │   0 │     0 │ 4.318 │   1.216 │     1 │     4 │     5 │     5 │     5 │ ▁  ▂▁▇ │  │
│ │           who26           │   0 │     0 │ 2.841 │   1.539 │     1 │     1 │     3 │     4 │     5 │ ▇▂ ▆▃▅ │  │
│ │           peso            │   0 │     0 │ 74.45 │   16.32 │  43.1 │ 64.38 │ 73.35 │ 83.48 │ 111.1 │ ▃▆▇▇▁▂ │  │
│ │         estatura          │   0 │     0 │ 1.628 │ 0.09428 │  1.45 │ 1.558 │  1.62 │  1.69 │  1.86 │ ▁▇▆▃▃▁ │  │
│ │            imc            │   0 │     0 │ 28.13 │   5.855 │ 17.71 │ 22.73 │ 27.98 │ 33.05 │ 39.45 │ ▆▆▇▇▇▃ │  │
│ │       circun_abdome       │   0 │     0 │ 90.91 │   14.82 │    56 │ 82.75 │    91 │    99 │   122 │ ▁▂▅▇▂▂ │  │
│ │        circun_pant        │   0 │     0 │ 36.55 │    3.94 │    28 │    34 │    36 │ 38.25 │    46 │ ▁▅▇▇▂▂ │  │
│ │            pas            │   0 │     0 │ 123.5 │   14.61 │   100 │ 117.5 │   120 │   130 │   180 │  ▅▇▅▂  │  │
│ │            pad            │   0 │     0 │ 73.18 │   18.52 │     0 │    70 │    80 │    80 │    90 │ ▁   ▆▇ │  │
│ │          hgs_dir          │   0 │     0 │ 31.83 │   10.18 │  14.7 │  23.9 │  29.9 │  38.7 │  61.8 │ ▅▇▆▅▁▁ │  │
│ │          hgs_esq          │   0 │     0 │ 29.57 │   8.644 │  14.2 │ 23.23 │  29.3 │ 35.38 │  55.7 │ ▅▇▇▆▁▁ │  │
│ │   cintura_altura_ratio    │   0 │     0 │ 56.03 │     9.7 │ 32.94 │ 49.55 │ 54.97 │ 62.72 │    75 │ ▁▅▇▇▅▃ │  │
│ └───────────────────────────┴─────┴───────┴───────┴─────────┴───────┴───────┴───────┴───────┴───────┴────────┘  │
│                                                     string                                                      │
│ ┏━━━━━━━━━━━┳━━━━┳━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━━┓  │
│ ┃           ┃    ┃      ┃           ┃           ┃           ┃           ┃ chars per ┃ words per ┃ total      ┃  │
│ ┃ column    ┃ NA ┃ NA % ┃ shortest  ┃ longest   ┃ min       ┃ max       ┃ row       ┃ row       ┃ words      ┃  │
│ ┡━━━━━━━━━━━╇━━━━╇━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━━┩  │
│ │  unidade  │  0 │    0 │  matriz   │ carolina  │ carolina  │  matriz   │      10.5 │       1.8 │         80 │  │
│ │           │    │      │           │ de jesus  │ de jesus  │           │           │           │            │  │
│ │   sexo    │  0 │    0 │ feminino  │ masculino │ feminino  │ masculino │      8.48 │         1 │         44 │  │
│ │ estado_ci │  0 │    0 │   viúvo   │ divorciad │  casado   │   viúvo   │       7.3 │         1 │         44 │  │
│ │    vil    │    │      │           │     o     │           │           │           │           │            │  │
│ │ escolarid │  0 │    0 │    não    │ fundament │ fundament │ superior  │      18.1 │         2 │         88 │  │
│ │    ade    │    │      │  estudou  │    al     │    al     │ incomplet │           │           │            │  │
│ │           │    │      │           │ incomplet │ completo  │     o     │           │           │            │  │
│ │           │    │      │           │     o     │           │           │           │           │            │  │
│ │ renda_men │  0 │    0 │  faltou   │   1 a 3   │   1 a 3   │ sem renda │      20.7 │       4.7 │        206 │  │
│ │    sal    │    │      │           │ salários  │ salários  │           │           │           │            │  │
│ │           │    │      │           │  mínimos  │  mínimos  │           │           │           │            │  │
│ │ tipo_mora │  0 │    0 │  cedida   │  própria  │  alugada  │  própria  │      6.93 │         1 │         44 │  │
│ │    dia    │    │      │           │           │           │           │           │           │            │  │
│ │ tempo_mor │  0 │    0 │   1 ano   │ não sabe  │   1 ano   │ não sabe  │      6.77 │         2 │         88 │  │
│ │   adia    │    │      │           │           │           │           │           │           │            │  │
│ │ cor_raca  │  0 │    0 │ preto (a) │  amarelo  │  amarelo  │ preto (a) │       9.3 │         2 │         88 │  │
│ │           │    │      │           │    (a)    │    (a)    │           │           │           │            │  │
│ │ funcao_tr │  0 │    0 │ cooperado │ individua │ cooperado │ individua │      9.39 │         1 │         44 │  │
│ │    ab     │    │      │           │     l     │           │     l     │           │           │            │  │
│ │ forma_rem │  0 │    0 │   fixa    │    por    │   fixa    │    por    │      11.6 │         2 │         86 │  │
│ │ uneracao  │    │      │           │ produção  │           │ produção  │           │           │            │  │
│ │ outro_tra │  0 │    0 │    sim    │    sim    │    não    │    sim    │         3 │         1 │         44 │  │
│ │     b     │    │      │           │           │           │           │           │           │            │  │
│ │ ja_trab_o │  0 │    0 │    não    │    não    │    não    │    sim    │         3 │         1 │         44 │  │
│ │ utro_loca │    │      │           │           │           │           │           │           │            │  │
│ │ l_recicla │    │      │           │           │           │           │           │           │            │  │
│ │    gem    │    │      │           │           │           │           │           │           │            │  │
│ │ utiliza_e │  0 │    0 │   nunca   │ as vezes  │ as vezes  │  sempre   │      6.02 │         1 │         46 │  │
│ │    pi     │    │      │           │           │           │           │           │           │            │  │
│ │ quais_epi │  0 │    0 │   Bota    │   Luva,   │   Bota    │    não    │      32.8 │       4.7 │        208 │  │
│ │     s     │    │      │           │ máscara,  │           │  utiliza  │           │           │            │  │
│ │           │    │      │           │   bota,   │           │   (puxa   │           │           │            │  │
│ │           │    │      │           │ avental,  │           │  fardo,   │           │           │            │  │
│ │           │    │      │           │ protetor  │           │ não fica  │           │           │            │  │
│ │           │    │      │           │ auricular │           │    na     │           │           │            │  │
│ │           │    │      │           │     ,     │           │ esteira)  │           │           │            │  │
│ │           │    │      │           │ capacete, │           │           │           │           │            │  │
│ │           │    │      │           │  óculos   │           │           │           │           │            │  │
│ │ recebe_tr │  0 │    0 │    sim    │    sim    │    não    │    sim    │         3 │         1 │         44 │  │
│ │ eino_segu │    │      │           │           │           │           │           │           │            │  │
│ │   rança   │    │      │           │           │           │           │           │           │            │  │
│ │ ja_sofreu │  0 │    0 │    não    │    não    │    não    │    sim    │         3 │         1 │         44 │  │
│ │ _acid_tra │    │      │           │           │           │           │           │           │            │  │
│ │     b     │    │      │           │           │           │           │           │           │            │  │
│ │ percepcao │  0 │    0 │   boas    │ regulares │   boas    │   ruins   │      4.82 │         1 │         44 │  │
│ │ _condicoe │    │      │           │           │           │           │           │           │            │  │
│ │  s_trab   │    │      │           │           │           │           │           │           │            │  │
│ │ exposicao │  0 │    0 │   nega    │  poeira,  │  cheiro   │  ruídos   │      23.6 │         3 │        131 │  │
│ │ _percebid │    │      │           │  cheiro,  │           │           │           │           │            │  │
│ │     a     │    │      │           │ cortantes │           │           │           │           │            │  │
│ │           │    │      │           │     ,     │           │           │           │           │            │  │
│ │           │    │      │           │ químicos, │           │           │           │           │            │  │
│ │           │    │      │           │  ruídos   │           │           │           │           │            │  │
│ │  tabacco  │  0 │    0 │    Não    │ Ex-fumant │ Ex-fumant │    Sim    │      3.16 │         1 │         44 │  │
│ │           │    │      │           │     e     │     e     │           │           │           │            │  │
│ │  bebida   │  0 │    0 │    Não    │    Sim    │    Não    │    Sim    │      3.02 │         1 │         45 │  │
│ │ freq_bebi │  0 │    0 │     ?     │  3x ou +  │ 1-2x sem  │   raro    │      7.07 │       1.9 │         85 │  │
│ │    da     │    │      │           │    sem    │           │           │           │           │            │  │
│ │ diagnosti │  0 │    0 │    DM     │ CA, pedra │ Aneurisma │ Trombose  │       6.7 │       1.5 │         65 │  │
│ │    co     │    │      │           │ vesícula, │ Cerebral  │     e     │           │           │            │  │
│ │           │    │      │           │ aderência │     e     │ alopécia  │           │           │            │  │
│ │           │    │      │           │ intestina │ Osteoporo │           │           │           │            │  │
│ │           │    │      │           │     l     │    se     │           │           │           │            │  │
│ │ acompanha │  0 │    0 │    sim    │    sim    │    não    │    sim    │         3 │         1 │         44 │  │
│ │ mento_med │    │      │           │           │           │           │           │           │            │  │
│ │    ico    │    │      │           │           │           │           │           │           │            │  │
│ │ medicamen │  0 │    0 │    não    │ losartana │  alenia   │ sertralin │         9 │       1.5 │         68 │  │
│ │    tos    │    │      │           │     ,     │           │    a e    │           │           │            │  │
│ │           │    │      │           │ atenolol  │           │ quetiapin │           │           │            │  │
│ │           │    │      │           │     e     │           │     a     │           │           │            │  │
│ │           │    │      │           │ anlodipin │           │           │           │           │            │  │
│ │           │    │      │           │     o     │           │           │           │           │            │  │
│ │ como_aval │  0 │    0 │    boa    │ muito boa │    boa    │  regular  │      5.77 │       1.2 │         53 │  │
│ │ ia_propri │    │      │           │           │           │           │           │           │            │  │
│ │  a_saude  │    │      │           │           │           │           │           │           │            │  │
│ │ imc_class │  0 │    0 │ sobrepeso │ obesidade │ eutrófico │ sobrepeso │      12.5 │         2 │         88 │  │
│ │     e     │    │      │           │  grau II  │           │           │           │           │            │  │
│ └───────────┴────┴──────┴───────────┴───────────┴───────────┴───────────┴───────────┴───────────┴────────────┘  │
╰────────────────────────────────────────────────────── End ──────────────────────────────────────────────────────╯

Sem valores ausentes.

## Selecionar apenas as colunas que não serão utilizadas

- x
- x

In [77]:
# Características demográficas
# df.columns.tolist() # descomentar apenas para ver a lista completa de colunas

# Normaliza os nomes das colunas para remover espaços extras (ex.: "idade ")
df.columns = [col.strip() if isinstance(col, str) else col for col in df.columns]

df_selecionada = df[
    [
        'idade',
        'sexo',
        'estado_civil',
        'escolaridade',
        'renda_mensal',
        'cor_raca',
        'tempo_trab_anos',
        'funcao_trab',
        'carga_horaria_horas_sem',
        'outro_trab',
        'tabacco',
        'bebida',
        'freq_bebida',
        'diagnostico',
        'medicamentos',
        'como_avalia_propria_saude',
        'who1',
        'who2',
        'who3',
        'who4',
        'who5',
        'who6',
        'who7',
        'who8',
        'who9',
        'who10',
        'who11',
        'who12',
        'who13',
        'who14',
        'who15',
        'who16',
        'who17',
        'who18',
        'who19',
        'who20',
        'who21',
        'who22',
        'who23',
        'who24',
        'who25',
        'who26',
        'peso',
        'estatura',
        'imc',
        'imc_classe',
        'circun_abdome',
        'circun_pant',
        'pas',
        'pad',
        'hgs_dir',
        'hgs_esq',
        'cintura_altura_ratio'
    ]
]

# Quantas linhas e colunas existem?
print(f'O número de linhas e colunas do dataset original é: {df.shape[0]} linhas e {df.shape[1]} colunas')
print(80 *'-')
print(f'O número de linhas e colunas do dataset selecionado é: {df_selecionada.shape[0]} linhas e {df_selecionada.shape[1]} colunas')

O número de linhas e colunas do dataset original é: 44 linhas e 66 colunas
--------------------------------------------------------------------------------
O número de linhas e colunas do dataset selecionado é: 44 linhas e 53 colunas

## Tratar coluna diagnóstico parar criar as variáveis DM2 e HAS. Tratar a coluna imc_classe para pegar a condição obesidade.

In [78]:

# Criação de novas colunas para indicar a presença de DM, HAS e obesidade
df_selecionada['DM2'] = (
    df_selecionada['diagnostico']
    .str.contains('DM', case=False, na=False)
    .astype(int)          # 1 = tem DM, 0 = não tem
)

df_selecionada['HAS'] = (
    df_selecionada['diagnostico']
    .str.contains('HAS', case=False, na=False)
    .astype(int)          # 1 = tem HAS, 0 = não tem
)

df_selecionada['obesidade'] = (
    df_selecionada['imc_classe']
    .str.contains('obesidade', case=False, na=False)
    .astype(int)          # 1 = tem obesidade, 0 = não tem
)

# Remover as colunas 'diagnostico' e 'imc_classe' do dataframe df_selecionada
df_selecionada = df_selecionada.drop(columns=['diagnostico', 'imc_classe'])

df_selecionada.head()

,idade,sexo,estado_civil,escolaridade,renda_mensal,cor_raca,tempo_trab_anos,funcao_trab,carga_horaria_horas_sem,outro_trab,...,circun_abdome,circun_pant,pas,pad,hgs_dir,hgs_esq,cintura_altura_ratio,DM2,HAS,obesidade
0,34,feminino,separado,médio completo,1 a 3 salários mínimos,preto (a),1.0,cooperado,40,sim,...,96.0,45.0,120,90,29.8,23.0,60.000000,0,0,1
1,59,masculino,divorciado,médio completo,mais de 3 salários,pardo (a),2.0,cooperado,56,não,...,82.0,39.0,110,70,22.9,31.2,52.229299,0,0,0
2,27,masculino,solteiro,superior completo,mais de 3 salários,pardo (a),1.0,cooperado,44,não,...,102.0,44.0,130,90,37.2,46.3,57.954545,0,0,1
3,40,masculino,solteiro,médio completo,1 a 3 salários mínimos,preto (a),1.0,cooperado,45,não,...,78.0,35.5,110,80,41.5,41.3,46.153846,0,0,0
4,23,masculino,solteiro,médio completo,mais de 3 salários,preto (a),2.0,cooperado,45,não,...,86.5,38.0,120,70,40.7,42.7,47.267760,0,0,0

Agora temos as comorbidades (DM2, HAS e obesidade) como variáveis binárias (0 = não tem, 1 = tem).

In [79]:
df_selecionada['medicamentos'].unique()

<ArrowStringArray>
[                             'não',                         'roacutan',
  'insulina, losartana e diurético',          'sertralina e quetiapina',
                        'omeprazol',     'hidroclorotiazida e atenolol',
                 'anticoncepcional',                        'não soube',
 'losartana, atenolol e anlodipino',            'não soube especificar',
 'hidroclorotiazida, enalapril + 1',                         'não sabe',
            'losartana e diurético',                          'dermato',
                           'alenia',    'losartana e hidroclorotiazida',
              'losartana e labirin',                 'para osteoporose']
Length: 18, dtype: str

In [80]:
# Tratar a coluna medicamentos para criar uma coluna binária indicando se a pessoa faz uso de medicamentos ou não
# df_selecionada['medicamentos'].unique() # descomentar apenas para ver a lista completa de medicamentos

padroes = {
    'ARB':          r'sartan',                                   # losartana, valsartana, olmesartana...
    'Diuretics':    r'diur[eé]tic|tiazid|clortalidona|furosemida|espironolactona|indapamida',
    'Beta_blockers':r'olol',                                     # atenolol, propranolol, metoprolol, carvedilol...
    'ACE_inhibitors': r'pril',                                   # enalapril, captopril, lisinopril, ramipril...
    'Metformin':    r'metformin|glifage',
    'CCB':          r'dipin|diltiazem|verapamil',                # anlodipino, nifedipino...
}

col = df_selecionada['medicamentos'].str.lower()

for classe, padrao in padroes.items():
    df_selecionada[classe] = col.str.contains(padrao, na=False, regex=True).astype(int)

# Remover coluna medicamentos do dataframe df_selecionada
df_selecionada = df_selecionada.drop(columns=['medicamentos'])

df_selecionada.head()

,idade,sexo,estado_civil,escolaridade,renda_mensal,cor_raca,tempo_trab_anos,funcao_trab,carga_horaria_horas_sem,outro_trab,...,cintura_altura_ratio,DM2,HAS,obesidade,ARB,Diuretics,Beta_blockers,ACE_inhibitors,Metformin,CCB
0,34,feminino,separado,médio completo,1 a 3 salários mínimos,preto (a),1.0,cooperado,40,sim,...,60.000000,0,0,1,0,0,0,0,0,0
1,59,masculino,divorciado,médio completo,mais de 3 salários,pardo (a),2.0,cooperado,56,não,...,52.229299,0,0,0,0,0,0,0,0,0
2,27,masculino,solteiro,superior completo,mais de 3 salários,pardo (a),1.0,cooperado,44,não,...,57.954545,0,0,1,0,0,0,0,0,0
3,40,masculino,solteiro,médio completo,1 a 3 salários mínimos,preto (a),1.0,cooperado,45,não,...,46.153846,0,0,0,0,0,0,0,0,0
4,23,masculino,solteiro,médio completo,mais de 3 salários,preto (a),2.0,cooperado,45,não,...,47.267760,0,0,0,0,0,0,0,0,0

# Criar a coluna aumentado risco para doenças cardio metabólicas

Para essa classificação será utilizada a relação cintura‑altura;

A relação cintura‑altura é calculada dividindo a circunferência da cintura pela altura; para adultos, manter o valor abaixo de 0,50 indica menor risco cardiometabólico segundo diretrizes como NICE e estudos de Ashwell & Gibson

< 0,40 — abaixo do adequado
0,40 a 0,49 — saudável
0,50 a 0,59 — risco aumentado
≥ 0,60 — risco elevado

In [81]:
df_selecionada['sexo'].unique()

<ArrowStringArray>
['feminino', 'masculino']
Length: 2, dtype: str

In [82]:
# Seleciona a coluna 'cintura_altura_ratio' e arredonda os valores para 2 casas decimais
# Converte a razão de porcentagem para proporção (ex.: 52.23 → 0.5223)
rce = df_selecionada['cintura_altura_ratio'].astype(float) / 100

# Binária: ≥ 0,50 = 1, < 0,50 = 0, ausente = NaN
df_selecionada['aumentado_cmr'] = np.where(rce.isna(), np.nan, (rce >= 0.50).astype(int))

# Move a coluna para logo depois de 'cintura_altura_ratio'
col = df_selecionada.pop('aumentado_cmr')
pos = df_selecionada.columns.get_loc('cintura_altura_ratio') + 1
df_selecionada.insert(pos, 'aumentado_cmr', col)

df_selecionada[['cintura_altura_ratio', 'aumentado_cmr']].head(10)

   cintura_altura_ratio  aumentado_cmr
0             60.000000            1.0
1             52.229299            1.0
2             57.954545            1.0
3             46.153846            0.0
4             47.267760            0.0
5             60.784314            1.0
6             63.870968            1.0
7             44.805195            0.0
8             45.698925            0.0
9             75.000000            1.0

# Calcular WHOQoL-BREF

In [83]:
who = df_selecionada.filter(regex='^who').astype(float).copy()

# 1. Valores fora de 1–5 viram ausentes (ELSE=SYSMIS)
who = who.where(who.isin([1, 2, 3, 4, 5]))

# 2. Inverter os itens 3, 4 e 26 (1=5, 2=4, 3=3, 4=2, 5=1)
for i in [3, 4, 26]:
    who[f'who{i}'] = 6 - who[f'who{i}']

# 3. Escores dos domínios (MEAN.n = média só se houver pelo menos n itens válidos) × 4
def media_min(df, itens, n_min):
    cols = [f'who{i}' for i in itens]
    media = df[cols].mean(axis=1)
    validos = df[cols].notna().sum(axis=1)
    return media.where(validos >= n_min) * 4

dominios = {
    'whoqol_fisico':      ([3, 4, 10, 15, 16, 17, 18], 6),           
    'whoqol_psicologico': ([5, 6, 7, 11, 19, 26], 5),                
    'whoqol_social':      ([20, 21, 22], 2),                        
    'whoqol_ambiente':    ([8, 9, 12, 13, 14, 23, 24, 25], 6),
}

for nome, (itens, n_min) in dominios.items():
    escore_4_20 = media_min(who, itens, n_min)
    # 4. Transformar para escala 0–100
    df_selecionada[nome] = round((escore_4_20 - 4) * (100 / 16), 2)

# 5. Excluir quem respondeu menos de 21 dos 26 itens (> 20% ausentes)
total_validos = who.notna().sum(axis=1)
df_selecionada['whoqol_n_validos'] = total_validos
df_selecionada.loc[total_validos < 21, list(dominios)] = np.nan

# remove as questões dos who e deixa apenas os dominios calculados
itens_who = df_selecionada.filter(regex=r'^who\d+$').columns
df_selecionada = df_selecionada.drop(columns=itens_who)
df_selecionada.filter(regex='^who').columns.tolist() # verifica quais colunas ficaram

['whoqol_fisico',
 'whoqol_psicologico',
 'whoqol_social',
 'whoqol_ambiente',
 'whoqol_n_validos']

# Verificando e organizando a ordem das variáveis que serão utilizadas no estudo

In [84]:
# df_selecionada.columns.tolist()
df_selecionada.loc[:, [
    # Sociodemograficos
    'idade',
    'sexo',
    'estado_civil',
    'escolaridade',
    'renda_mensal',
    'cor_raca',
    # Ocupacionais
    'tempo_trab_anos',
    'funcao_trab',
    'carga_horaria_horas_sem',
    'outro_trab',
    # estilo de vida
    'tabacco',
    'bebida',
    'freq_bebida',
    'como_avalia_propria_saude',
    # antropometria e clinica
    'peso',
    'estatura',
    'imc',
    'circun_abdome',
    'circun_pant',
    'pas',
    'pad',
    'hgs_dir',
    'hgs_esq',
    'cintura_altura_ratio',
    # Comorbidades
    'aumentado_cmr',
    'DM2',
    'HAS',
    'obesidade',
    # medicamentos
    'ARB',
    'Diuretics',
    'Beta_blockers',
    'ACE_inhibitors',
    'Metformin',
    'CCB',
    # escore de QoL
    'whoqol_fisico',
    'whoqol_psicologico',
    'whoqol_social',
    'whoqol_ambiente',
    'whoqol_n_validos'    
]]

,idade,sexo,estado_civil,escolaridade,renda_mensal,cor_raca,tempo_trab_anos,funcao_trab,carga_horaria_horas_sem,outro_trab,...,Diuretics,Beta_blockers,ACE_inhibitors,Metformin,CCB,whoqol_fisico,whoqol_psicologico,whoqol_social,whoqol_ambiente,whoqol_n_validos
0,34,feminino,separado,médio completo,1 a 3 salários mínimos,preto (a),1.000000,cooperado,40,sim,...,0,0,0,0,0,71.43,70.83,83.33,78.12,26
1,59,masculino,divorciado,médio completo,mais de 3 salários,pardo (a),2.000000,cooperado,56,não,...,0,0,0,0,0,100.00,83.33,100.00,93.75,26
2,27,masculino,solteiro,superior completo,mais de 3 salários,pardo (a),1.000000,cooperado,44,não,...,0,0,0,0,0,78.57,58.33,75.00,75.00,26
3,40,masculino,solteiro,médio completo,1 a 3 salários mínimos,preto (a),1.000000,cooperado,45,não,...,0,0,0,0,0,78.57,95.83,100.00,78.12,26
4,23,masculino,solteiro,médio completo,mais de 3 salários,preto (a),2.000000,cooperado,45,não,...,0,0,0,0,0,75.00,83.33,66.67,90.62,26
5,65,feminino,casado,fundamental incompleto,1 a 3 salários mínimos,pardo (a),2.000000,cooperado,44,não,...,1,0,0,0,0,85.71,100.00,100.00,100.00,26
6,54,feminino,casado,fundamental incompleto,1 a 3 salários mínimos,branco (a),5.000000,cooperado,60,não,...,0,0,0,0,0,46.43,66.67,100.00,75.00,26
7,49,feminino,solteiro,fundamental completo,1 a 3 salários mínimos,preto (a),2.000000,cooperado,45,não,...,0,0,0,0,0,100.00,100.00,75.00,100.00,26
8,27,masculino,casado,médio completo,1 a 3 salários mínimos,branco (a),2.678571,cooperado,50,não,...,0,0,0,0,0,85.71,100.00,100.00,100.00,26
9,55,feminino,casado,médio completo,1 a 3 salários mínimos,branco (a),2.678571,cooperado,40,não,...,1,1,0,0,0,78.57,70.83,83.33,81.25,26
10,34,feminino,solteiro,médio incompleto,1 a 3 salários mínimos,branco (a),1.000000,cooperado,35,não,...,0,0,0,0,0,92.86,62.50,75.00,87.50,26
11,32,feminino,solteiro,fundamental incompleto,1 a 3 salários mínimos,preto (a),1.000000,cooperado,35,não,...,0,0,0,0,0,85.71,83.33,75.00,56.25,26
12,51,masculino,separado,fundamental completo,1 a 3 salários mínimos,pardo (a),2.678571,cooperado,74,não,...,0,0,0,0,0,71.43,95.83,100.00,100.00,26
13,55,feminino,casado,fundamental incompleto,1 a 3 salários mínimos,pardo (a),2.678571,cooperado,30,não,...,0,0,0,0,0,82.14,66.67,91.67,87.50,26
14,31,feminino,solteiro,médio completo,1 a 3 salários mínimos,pardo (a),7.000000,cooperado,35,não,...,0,0,0,0,0,71.43,95.83,100.00,93.75,26
15,28,masculino,casado,médio incompleto,faltou,branco (a),2.678571,cooperado,70,não,...,0,0,0,0,0,71.43,91.67,100.00,90.62,26
16,32,masculino,solteiro,médio incompleto,1 a 3 salários mínimos,pardo (a),2.678571,cooperado,40,não,...,0,0,0,0,0,64.29,100.00,100.00,100.00,26
17,63,feminino,solteiro,fundamental incompleto,1 a 3 salários mínimos,preto (a),1.000000,cooperado,30,não,...,0,0,0,0,0,100.00,100.00,58.33,96.88,26
18,71,feminino,separado,médio completo,1 a 3 salários mínimos,branco (a),2.678571,cooperado,40,não,...,0,1,0,0,1,71.43,83.33,33.33,100.00,26
19,44,feminino,casado,fundamental incompleto,1 a 3 salários mínimos,pardo (a),1.000000,cooperado,40,não,...,0,0,0,0,0,64.29,50.00,33.33,65.62,26
20,67,masculino,separado,não estudou,1 a 3 salários mínimos,preto (a),2.678571,cooperado,40,não,...,0,0,0,0,0,92.86,100.00,100.00,87.50,26
21,38,masculino,solteiro,fundamental incompleto,mais de 3 salários,branco (a),3.000000,cooperado,35,não,...,0,0,0,0,0,89.29,75.00,66.67,81.25,26
22,35,masculino,solteiro,médio completo,1 a 3 salários mínimos,pardo (a),2.678571,cooperado,40,não,...,0,0,0,0,0,42.86,62.50,75.00,71.88,26
23,58,masculino,separado,fundamental incompleto,1 a 3 salários mínimos,preto (a),1.000000,cooperado,35,não,...,1,0,1,0,0,71.43,83.33,58.33,62.50,26
24,57,feminino,solteiro,fundamental incompleto,1 a 3 salários mínimos,branco (a),2.678571,cooperado,40,não,...,0,0,0,0,0,78.57,91.67,100.00,87.50,26
25,29,masculino,solteiro,superior completo,1 a 3 salários mínimos,preto (a),8.000000,cooperado,35,sim,...,0,0,0,0,0,82.14,58.33,83.33,84.38,26
26,67,masculino,solteiro,fundamental incompleto,mais de 3 salários,preto (a),2.678571,cooperado,40,não,...,0,0,0,0,0,71.43,70.83,75.00,100.00,26
27,48,feminino,separado,fundamental incompleto,mais de 3 salários,pardo (a),5.000000,individual,56,não,...,0,0,0,0,0,92.86,75.00,66.67,62.50,26
28,61,feminino,solteiro,fundamental completo,1 a 3 salários mínimos,pardo (a),2.678571,individual,30,não,...,1,0,0,0,0,92.86,66.67,8.33,68.75,26
29,77,feminino,viúvo,superior completo,1 a 3 salários mínimos,branco (a),2.678571,individual,60,não,...,0,0,0,0,0,42.86,83.33,33.33,75.00,26
30,36,masculino,casado,médio incompleto,1 a 3 salários mínimos,branco (a),4.000000,individual,70,não,...,0,0,0,0,0,28.57,75.00,8.33,59.38,26
31,57,feminino,casado,fundamental completo,1 a 3 salários mínimos,pardo (a),2.000000,individual,60,sim,...,0,0,0,0,0,96.43,83.33,50.00,87.50,26
32,37,feminino,solteiro,médio completo,1 a 3 salários mínimos,pardo (a),1.000000,individual,60,não,...,0,0,0,0,0,89.29,58.33,91.67,78.12,26
33,33,feminino,solteiro,superior incompleto,1 a 3 salários mínimos,pardo (a),3.000000,individual,60,não,...,0,0,0,0,0,85.71,66.67,66.67,53.12,26
34,65,feminino,solteiro,médio completo,1 a 3 salários mínimos,branco (a),2.678571,individual,20,sim,...,0,0,0,0,0,60.71,33.33,16.67,53.12,26
35,38,feminino,casado,fundamental completo,1 a 3 salários mínimos,preto (a),1.000000,individual,45,não,...,0,0,0,0,0,100.00,100.00,100.00,100.00,26
36,27,masculino,solteiro,médio incompleto,1 a 3 salários mínimos,pardo (a),2.000000,individual,50,sim,...,0,0,0,0,0,92.86,100.00,100.00,100.00,26
37,60,masculino,casado,fundamental completo,1 a 3 salários mínimos,pardo (a),2.000000,individual,40,não,...,0,0,0,0,0,100.00,83.33,33.33,84.38,26
38,58,feminino,casado,médio completo,1 a 3 salários mínimos,pardo (a),3.000000,individual,60,não,...,1,0,0,0,0,64.29,79.17,66.67,96.88,26
39,65,masculino,casado,fundamental incompleto,1 a 3 salários mínimos,pardo (a),3.000000,individual,50,não,...,0,0,0,0,0,71.43,87.50,83.33,71.88,26
40,41,masculino,solteiro,fundamental incompleto,1 a 3 salários mínimos,pardo (a),2.678571,individual,56,sim,...,0,0,0,0,0,71.43,79.17,25.00,43.75,26
41,47,masculino,casado,fundamental incompleto,sem renda,amarelo (a),4.000000,individual,18,não,...,0,0,0,0,0,50.00,41.67,66.67,43.75,26
42,29,feminino,casado,superior completo,mais de 3 salários,pardo (a),6.000000,individual,44,sim,...,0,0,0,0,0,78.57,66.67,66.67,87.50,26
43,18,masculino,solteiro,fundamental incompleto,1 a 3 salários mínimos,pardo (a),2.678571,individual,40,sim,...,0,0,0,0,0,64.29,79.17,91.67,81.25,26

# Salvar `df_selecionada` em um csv (`df_analise`) para analise

In [85]:
# Salvando o DataFrame em um novo arquivo CSV
df_selecionada.to_csv('data\\df_analise.csv', index=False)

## Final dataprep!!!

![Final dataprep](https://i.pinimg.com/736x/b8/ec/19/b8ec194b5c8ac8eef2549ad717bed5e9.jpg)